# Generated by Django 5.0 on 2024-09-26 20:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "specialization",
                    models.CharField(max_length=255, verbose_name="Specialization"),
                ),
                ("bio", models.TextField(verbose_name="Bio")),
                (
                    "profile_picture",
                    models.ImageField(
                        upload_to="doctor_pictures/", verbose_name="Profile Picture"
                    ),
                ),
                ("availability", models.TextField(verbose_name="Availability")),
                (
                    "rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                        verbose_name="Rating",
                    ),
                ),
            ],
            options={
                "verbose_name": "Doctor",
                "verbose_name_plural": "Doctors",
                "db_table": "doctor",
            },
        ),
    ]
