# Generated by Django 5.0 on 2024-12-03 03:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Title of the book", max_length=255),
                ),
                (
                    "author",
                    models.CharField(help_text="Author of the book", max_length=255),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="A brief summary or description of the book",
                        null=True,
                    ),
                ),
                (
                    "published_date",
                    models.DateField(
                        blank=True, help_text="Publication date of the book", null=True
                    ),
                ),
                (
                    "isbn",
                    models.CharField(
                        blank=True,
                        help_text="International Standard Book Number (ISBN)",
                        max_length=13,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                10, message="ISBN must be at least 10 characters long"
                            ),
                            django.core.validators.MaxValueValidator(
                                13,
                                message="ISBN cannot be more than 13 characters long",
                            ),
                        ],
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="English",
                        help_text="Language of the book",
                        max_length=100,
                    ),
                ),
                (
                    "pages",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Total number of pages in the book",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, message="Number of pages must be at least 1"
                            )
                        ],
                    ),
                ),
                (
                    "cover_image",
                    models.URLField(
                        blank=True, help_text="URL of the book's cover image", null=True
                    ),
                ),
                (
                    "file",
                    models.URLField(
                        blank=True,
                        help_text="URL of the book file (PDF, ePub, etc.)",
                        null=True,
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        help_text="Tag to categorize the book (e.g., fiction, self-help, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates if the book is available for reading",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the book record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the book record was last updated",
                    ),
                ),
            ],
            options={
                "verbose_name": "Book",
                "verbose_name_plural": "Books",
                "ordering": ["title"],
            },
        ),
    ]
