# Generated by Django 5.0 on 2024-12-03 04:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.IntegerField(
                blank=True,
                help_text="International Standard Book Number (ISBN)",
                null=True,
                unique=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        10, message="ISBN must be at least 10 characters long"
                    ),
                    django.core.validators.MaxValueValidator(
                        13, message="ISBN cannot be more than 13 characters long"
                    ),
                ],
            ),
        ),
    ]
