# Generated by Django 5.0 on 2024-12-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0003_alter_book_isbn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(
                blank=True,
                help_text="International Standard Book Number (ISBN)",
                max_length=13,
                null=True,
                unique=True,
            ),
        ),
    ]
