# Generated by Django 5.0 on 2024-12-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_passwordresetotp"),
    ]

    operations = [
        migrations.CreateModel(
            name="Concern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Concern Name"
                    ),
                ),
            ],
            options={
                "verbose_name": "Concern",
                "verbose_name_plural": "Concerns",
                "db_table": "concern",
            },
        ),
        migrations.AddField(
            model_name="userprofile",
            name="concerns",
            field=models.ManyToManyField(
                blank=True, to="accounts.concern", verbose_name="Concerns"
            ),
        ),
    ]
